# NumPy  
NumPy is a Python library

numerical python

[ read more about NumPy ](https://numpy.org/)

##install and import

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


0D array ---> scalar

1D array ---> vector

2D array ---> matrix

An array with more than two axes ---> tensor

![](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

![](https://pbs.twimg.com/media/F0a1yV5WwAAig9U.jpg:large)

## array

In [ ]:
np.array([[1,2,3],
         [1,2,3]])

In [ ]:
a = np.array([[1,2,3],
             [1,2,3],
             [1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#dimensions
a.ndim

2



```
#np.array([])
```



In [ ]:
list1 = [1,2,3,4]
x = np.array(list1)
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
x.ndim

1

##shape and resize

In [ ]:
np.shape(x)

(4,)

In [ ]:
y = np. array([[1,2,3],[2,1,1]])
np.shape(y)
#print(y)

(2, 3)

In [ ]:
y.ndim

2

In [ ]:
print(x)

[1 2 3 4]


In [ ]:
np.resize(x,(3,3))

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1]])

## ones

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones((2,2),int)

array([[1, 1],
       [1, 1]])

## zeros

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2),int)

array([[0, 0],
       [0, 0]])

In [ ]:
np.zeros((2,3),int)


array([[0, 0, 0],
       [0, 0, 0]])

##repeat

In [ ]:
np.repeat([1,2,3,4],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [ ]:
([1,2,3,4]*4)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

## full

In [ ]:
np.full(11,8.3)

array([8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3])

In [ ]:
np.full((4,3),3.5)

array([[3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5]])

##vertical stack
 vstack

In [ ]:
a = np.ones((2,2), int)
b = np.full((2,2),6)
print("a:",a)
print("b:",b)

a: [[1 1]
 [1 1]]
b: [[6 6]
 [6 6]]


In [ ]:
print(a.ndim)

2


In [ ]:
np.vstack([a,b])


array([[1, 1],
       [1, 1],
       [6, 6],
       [6, 6]])

##horizontal stack
hstack

In [ ]:
np.hstack([a,b])

array([[1, 1, 6, 6],
       [1, 1, 6, 6]])

## Operations

In [ ]:
x = np.array([8,9,6])
y = np.array([2,6,3])
print(x)
print(y)

[8 9 6]
[2 6 3]


In [ ]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[10 15  9]
[6 3 3]
[16 54 18]
[4.  1.5 2. ]


In [ ]:
print('plus:', x + y)
print('minus:', x - y)
print('multiplication:', x * y)
print('division:', x / y)

plus: [10 15  9]
minus: [6 3 3]
multiplication: [16 54 18]
division: [4.  1.5 2. ]


## Multiplying matrices:

Multiplying matrices:

![](https://www.mathsisfun.com/algebra/images/matrix-multiply-constant.svg)



---


![](https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg)


(1, 2, 3) • (7, 9, 11) = 1×7 + 2×9 + 3×11 = 58

.

.

.



![](https://www.mathsisfun.com/algebra/images/matrix-multiply-b.svg)

(1, 2, 3) • (8, 10, 12) = 1×8 + 2×10 + 3×12 = 64


(4, 5, 6) • (7, 9, 11) = 4×7 + 5×9 + 6×11 = 139


(4, 5, 6) • (8, 10, 12) = 4×8 + 5×10 + 6×12 = 154

![](https://www.mathsisfun.com/algebra/images/matrix-multiply-c.svg)

In [ ]:
#np.dot
x1 = np.array([[2,3,2],[1,3,2],[4,1,3]])
x2 = np.array([[4,5,3],[2,4,1]])
print('x1:', x1)
print('x2',x2)
print('-----------------')
x3 = np.dot(x1,x2)
print('answer:',x3)

x1: [[2 3 2]
 [1 3 2]
 [4 1 3]]
x2 [[4 5 3]
 [2 4 1]]
-----------------


ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
#reshape
x2 = np.array([[4,5,3],[2,4,1]])
print(x2)
print('---------------')
x5 = np.reshape(x2,(3,2))
print(x5)

[[4 5 3]
 [2 4 1]]
---------------
[[4 5]
 [3 2]
 [4 1]]


In [ ]:
x1 = np.array([[2,3,2],[1,3,2],[4,1,3]])
x2 = np.array([[4,5,3],[2,4,1],[3,1,5]])
print('x1:', x1)
print('x2',x2)
print('-----------------')
x3 = np.dot(x1,x2)
print('answer:',x3)

x1: [[2 3 2]
 [1 3 2]
 [4 1 3]]
x2 [[4 5 3]
 [2 4 1]
 [3 1 5]]
-----------------
answer: [[20 24 19]
 [16 19 16]
 [27 27 28]]


![](https://datascienceparichay.com/wp-content/uploads/2021/07/transpose-a-numpy-array.png)

In [ ]:
#T transpose
x4 = np.array([[2,4,1],[3,1,2]])
print(x4)
print('---------------')
print(x4.T)

[[2 4 1]
 [3 1 2]]
---------------
[[2 3]
 [4 1]
 [1 2]]


## sum

In [ ]:
r = np.array([1,3,3,6,7,8,9])
print(r)

[1 3 3 6 7 8 9]


In [ ]:
r.sum()

37

## mean

In [ ]:
print(r)

[1 3 3 6 7 8 9]


In [ ]:
np.mean(r)

5.285714285714286

## median

![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Finding_the_median.png/1200px-Finding_the_median.png)

In [ ]:
np.median(r)

6.0

In [ ]:
r = np.array([1,2,3,4,5,6,8,9])

In [ ]:
np.median(r)

4.5

In [ ]:
#odd
f = np.array([1,6,2,4,3])
f

In [ ]:
f = np.sort(f)
f

array([1, 2, 3, 4, 6])

In [ ]:
np.median(f)

3.0

In [ ]:
#even
f = np.array([1,6,10,4])

In [ ]:
f = np.sort(f)
f

array([ 1,  4,  6, 10])

In [ ]:
np.median(f)

5.0

##standard deviation

std ----> standard deviation (انحراف معیار)


![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgL_K-Z2GeGOs-Em82UNM_DcSxNc2u4NIIPr88pgQqhB0d6KTZgRGfpuSG8JriMf7TZvk&usqp=CAU)



In [ ]:
np.std(r)

2.762725657973388

##Slicing in numpy

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr1[1:5])

[2 3 4 5]


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr2[4:])

[5 6 7]


In [ ]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr3[:4])

[1 2 3 4]


In [ ]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[-3:-1])

[5 6]


In [ ]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr5[1:5:2])

[2 4]


In [ ]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr6[::2])

[1 3 5 7]


##Slicing 2-D Arrays

In [ ]:
#From the second element, slice elements from index 1 to index 4 (not included):

arr7 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr7[1, 1:4])

[7 8 9]


In [ ]:
#From both elements, return index 2:
arr8 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr8[0:2, 2])

[3 8]


In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr9 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr9)
print('--------------')
print(arr9[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
--------------
[[2 3 4]
 [7 8 9]]


## New Section

In [ ]:
x1 = np.array([[2,3,2],[1,3,2],[4,1,3]])
print(x1)
print('------------')
print(x1[x1>2])

[[2 3 2]
 [1 3 2]
 [4 1 3]]
------------


array([3, 3, 4, 3])

In [ ]:
x1[x1>2] = 0
print(x1)

[[2 0 2]
 [1 0 2]
 [0 1 0]]


In [ ]:
x1 = np.array([[2,3,2],[1,3,2],[4,1,3]])
print(x1)

print('---------')

x1[0,0:2] = 0
print(x1)


[[2 3 2]
 [1 3 2]
 [4 1 3]]
---------
[[0 0 2]
 [1 3 2]
 [4 1 3]]


## numpy.arange



```
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
```



In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy.linspace



```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
```



In [ ]:
np.linspace?

In [ ]:
np.linspace(0,10,11,dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##concatenate

In [ ]:
z1 = np.array([2,3,1,4])
z2 = np.array([1,2,4,4])
np.concatenate((z1,z2))

array([2, 3, 1, 4, 1, 2, 4, 4])

##argmin/argmax

In [ ]:
#0,1,2,3
w=[2,9,3,7]

In [ ]:
k = np.array([11,7,21,9,5,17])
print(np.argmin(k))
print(np.argmax(k))

4
2
